version: "3.3"
services:

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data

  hello-world-spring-boot:
    image: tan66/hello-world-spring-boot:v1
    ports:
      - 5000:8080
    depends_on:
      - nexus

volumes:
  nexus-data: